[platformio]
default_envs = master


; ============================================================
; Common ESP32 settings
; ============================================================

[env:esp32_base]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200


; ============================================================
; MASTER
; ============================================================

[env:master]
extends = env:esp32_base

build_src_filter =
    +<master/>
    -<sensor/>
    -<actuator/>

build_flags =
    -D NODE_MASTER

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306


; ============================================================
; SENSOR
; ============================================================

[env:sensor]
extends = env:esp32_base

build_src_filter =
    -<master/>
    +<sensor/>
    -<actuator/>

build_flags =
    -D NODE_SENSOR

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306


; ============================================================
; ACTUATOR
; ============================================================

[env:actuator]
extends = env:esp32_base

build_src_filter =
    -<master/>
    -<sensor/>
    +<actuator/>

build_flags =
    -D NODE_ACTUATOR

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306